# Generated by Django 6.0.3 on 2026-07-31 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerformanceTelemetryAlertSummary",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("repository", models.CharField(max_length=50)),
                ("framework", models.CharField(max_length=255)),
                ("prev_push_revision", models.CharField(max_length=40)),
                ("prev_push_timestamp", models.DateTimeField()),
                ("push_revision", models.CharField(max_length=40)),
                ("push_timestamp", models.DateTimeField(db_index=True)),
                (
                    "original_push_revision",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                (
                    "original_push_timestamp",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "original_prev_push_revision",
                    models.CharField(default=None, max_length=40, null=True),
                ),
                (
                    "original_prev_push_timestamp",
                    models.DateTimeField(default=None, null=True),
                ),
                ("manually_created", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "assignee_email",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("sheriffed", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("triage_due_date", models.DateTimeField(default=None, null=True)),
                ("first_triaged", models.DateTimeField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Untriaged"),
                            (1, "Downstream"),
                            (2, "Reassigned"),
                            (3, "Invalid"),
                            (4, "Improvement"),
                            (5, "Investigating"),
                            (6, "Won't fix"),
                            (7, "Fixed"),
                            (8, "Backed out"),
                            (9, "Infra"),
                        ],
                        default=0,
                    ),
                ),
                ("bug_number", models.PositiveIntegerField(null=True)),
                ("bug_due_date", models.DateTimeField(default=None, null=True)),
                ("bug_updated", models.DateTimeField(null=True)),
                ("issue_tracker", models.CharField(default="Bugzilla", max_length=255)),
                ("bugs_modified", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "performance_telemetry_alert_summary",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "repository",
                            "framework",
                            "prev_push_revision",
                            "push_revision",
                        ),
                        name="unique_telemetry_alert_summary_push_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceTelemetrySignature",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("Nightly", "Mozilla-central Builds"),
                            ("Beta", "Mozilla-beta Builds"),
                            ("Release", "Mozilla-release Builds"),
                        ],
                        max_length=30,
                    ),
                ),
                ("platform", models.CharField(max_length=80)),
                ("probe", models.CharField(max_length=80)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Label of the probe for labeled probe types (e.g. labeled_timing_distribution). Each label of those probes holds its own timeseries so it needs its own signature. Empty for unlabeled probes.",
                        max_length=255,
                    ),
                ),
                (
                    "probe_type",
                    models.CharField(
                        choices=[
                            (
                                "Glean",
                                "Probes that are from the Glean Telemetry System",
                            ),
                            (
                                "Legacy",
                                "Probes that are from the Legacy Telemetry System",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        default="",
                        help_text="Application that runs the signature's tests. Generally used to record browser's name, but not necessarily.",
                        max_length=80,
                    ),
                ),
                ("lower_is_better", models.BooleanField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "performance_telemetry_signature",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "channel",
                            "probe",
                            "probe_type",
                            "platform",
                            "application",
                            "label",
                        ),
                        name="unique_telemetry_signature",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceTelemetryAlert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_regression", models.BooleanField(null=True)),
                ("starred", models.BooleanField(default=False)),
                (
                    "classifier_email",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("sheriffed", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("first_triaged", models.DateTimeField(default=None, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "NEW"),
                            (1, "FIXED"),
                            (2, "INVALID"),
                            (5, "WONTFIX"),
                            (3, "INACTIVE"),
                            (4, "DUPLICATE"),
                            (6, "WORKSFORME"),
                            (7, "INCOMPLETE"),
                            (8, "MOVED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "amount_pct",
                    models.FloatField(help_text="Amount in percentage that series has changed"),
                ),
                (
                    "amount_abs",
                    models.FloatField(help_text="Absolute amount that series has changed"),
                ),
                (
                    "prev_value",
                    models.FloatField(help_text="Previous value of series before change"),
                ),
                (
                    "new_value",
                    models.FloatField(help_text="New value of series after change"),
                ),
                (
                    "t_value",
                    models.FloatField(
                        help_text="t value out of analysis indicating confidence that change is 'real'",
                        null=True,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="A value that indicates the confidence of the alert (specific to the detection method used)",
                        null=True,
                    ),
                ),
                ("detection_method", models.CharField(max_length=100, null=True)),
                (
                    "noise_profile",
                    models.CharField(
                        choices=[
                            (
                                "SKEWED",
                                "Samples are heavily found on one side of the mean.",
                            ),
                            (
                                "OUTLIERS",
                                "There are more outliers than should be expected from a normal distribution.",
                            ),
                            (
                                "MODAL",
                                "There are multiple areas where most values are found rather than only one.",
                            ),
                            ("OK", "No issues were found."),
                            ("N/A", "Could not compute a noise profile."),
                        ],
                        default="N/A",
                        help_text="The noise profile of the data which precedes this alert.",
                        max_length=30,
                    ),
                ),
                ("manually_created", models.BooleanField(default=False)),
                ("sustained", models.BooleanField(default=False)),
                ("direction", models.CharField(max_length=100, null=True)),
                (
                    "prev_median",
                    models.FloatField(
                        default=0.0,
                        help_text="Previous median value of series before change",
                    ),
                ),
                (
                    "new_median",
                    models.FloatField(
                        default=0.0, help_text="New median value of series after change"
                    ),
                ),
                (
                    "prev_p05",
                    models.FloatField(
                        default=0.0,
                        help_text="Previous P05 value of series before change",
                    ),
                ),
                (
                    "new_p05",
                    models.FloatField(
                        default=0.0, help_text="New P05 value of series after change"
                    ),
                ),
                (
                    "prev_p95",
                    models.FloatField(
                        default=0.0,
                        help_text="Previous P95 value of series before change",
                    ),
                ),
                (
                    "new_p95",
                    models.FloatField(
                        default=0.0, help_text="New P95 value of series after change"
                    ),
                ),
                ("bug_number", models.PositiveIntegerField(null=True)),
                ("notified", models.BooleanField(default=False)),
                ("bug_modified", models.BooleanField(default=True)),
                (
                    "additional_data",
                    models.JSONField(
                        default=dict,
                        help_text="This field can be used to store additional data in JSON format that doesn't fit in any of the other fields. Custom CDP techniques can use this field to store extra non-standard data.",
                    ),
                ),
                (
                    "related_summary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_alerts",
                        to="model.performancetelemetryalertsummary",
                    ),
                ),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="model.performancetelemetryalertsummary",
                    ),
                ),
                (
                    "series_signature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="model.performancetelemetrysignature",
                    ),
                ),
            ],
            options={
                "db_table": "performance_telemetry_alert",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("summary", "series_signature"),
                        name="unique_telemetry_alert_per_summary",
                    )
                ],
            },
        ),
    ]
